charts:
  # list of charts by name
  # each name should be a directory containing a helm chart
  - name: deploy/helm/cloud-native-demo
    # The git repo whose gh-pages contains the charts. This can be a local
    # path such as "." as well but if matching <organization>/<repo> will be
    # assumed to be a separate GitHub repository.
    repo:
      git: cypherfox/charts
      published: https://cypherfox.github.io/charts