{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ include "emojivoto.fullname" . }}-emoji-svc
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: emoji-svc
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ include "emojivoto.fullname" . }}-voting-svc
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: voting-svc
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ include "emojivoto.fullname" . }}-web-svc
  labels:
    {{- include "emojivoto.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: web-svc
  type: ClusterIP
