apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: pod-worker
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/status"]
  verbs: ["get", "watch", "list"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-pods
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: bugsim-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pod-worker
  apiGroup: rbac.authorization.k8s.io