apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: pod-worker
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: access-pods
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: bugsim-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pod-worker
  apiGroup: rbac.authorization.k8s.io