# Default values for emojivoto.

namespace:
  name: emojivoto
  create: false


imagePullSecrets: []

serviceAccount:
  # Specifies whether a set of service accounts should be created. Otherwise "default" is used.
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The names of the service accounts to use.
  emojiName: emojivoto-emoji
  voteName:  emojivoto-vote
  webName:   emojivoto-web

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

#----------------------------------------------
# delete below this line

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
