name: Lint and Test Charts

on: [push]

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing 
        uses: helm/chart-testing-action@v2.2.0

      #- name: Run chart-testing (list-changed)
      #  id: list-changed
      #  run: |
      #    changed=$(ct list-changed --chart-dirs deploy/helm/cloud-native-demo)
      #    if [[ -n "$changed" ]]; then
      #      echo "::set-output name=changed::true"
      #    fi

      - name: Run chart-testing (lint)
        id: ct-lint
        run: |
          ct lint \
            --charts /home/runner/work/cloud-native-demo/cloud-native-demo/deploy/helm/cloud-native-demo \
            --chart-repos grafana=https://grafana.github.io/helm-charts \
		        --chart-repos linkerd=https://helm.linkerd.io/stable \
		        --validate-maintainers=false
            

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.19.8
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.19.8
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@main
        with:
          command: install
          config: .github/ct.yaml