name: Lint and Test Charts

on: [push]

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.7.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1

      - name: Set up chart-testing 
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --charts /home/runner/work/cloud-native-demo/cloud-native-demo/deploy/helm/cloud-native-demo --chart-repos grafana=https://grafana.github.io/helm-charts --chart-repos linkerd=https://helm.linkerd.io/stable
        id: ct-lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        #if: steps.list-changed.outputs.changed == 'true'

#      - name: Run chart-testing (install)
#        run: ct install --charts /home/runner/work/cloud-native-demo/cloud-native-demo/deploy/helm/cloud-native-demo --chart-repos grafana=https://grafana.github.io/helm-charts --chart-repos linkerd=https://helm.linkerd.io/stable  --namespace cloud-native-demo

